version: '2'
services: 
    mysql:
        container_name: mysql_schuelerverwaltung
        restart: always
        image: mysql:latest
        environment: 
            MYSQL_DATABASE: schueler
            MYSQL_ROOT_PASSWORD: test_pass
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes: 
            - ./database:/var/lib/mysql
        ports: 
            - '3306:3306'
        expose: 
            - '3306'